export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const CATEGORIES = "CATEGORIES";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CHILD_CATEGORIES = "GET_CHILD_CATEGORIES";
